services:
  nestjs-app:
    container_name: nestjs-app-task-container-v1.22.0
    build:
      context: .
      dockerfile: Dockerfile
    image: firashusawi/nestjs-app-task:v1.22.0
    ports:
      - '3000:3000'
    volumes:
      - ./dist:/dist
    command: node main.js
